services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      TZ: Europe/Minsk
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      TZ: Europe/Minsk
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    depends_on:
      - kafka
    environment:
      TZ: Europe/Minsk
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - "8082:8080"

  weather-app:
    build: .
    container_name: weather-app
    network_mode: "host"
    environment:
      TZ: Europe/Minsk
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/weather_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "2223399z"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092

  weather-consumer:
    build: ./weather-consumer
    container_name: weather-consumer
    network_mode: "host"
    environment:
      TZ: Europe/Minsk
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/weather_logs_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "2223399z"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092